import { useState } from "react"
import { Search, Sparkles, ArrowRight, BarChart, Clock, Star, Users, FileText, Brain, Database, BookOpen, RefreshCw, GitCompare, Image, MessageSquare, ScanLine, PenTool, BarChart3, Bot } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { AppSidebar } from "@/components/AppSidebar"
import { ProfileDropdown } from "@/components/ProfileDropdown"
import { Link } from "react-router-dom"

// Import tool images
import itemGenerationImage from "@/assets/item-generation.png"
import itemWriterImage from "@/assets/item-writer.png"
import itemMetadataImage from "@/assets/item-metadata.png"
import courseGeneratorImage from "@/assets/course-generator.png"
import itemRewriterImage from "@/assets/item-rewriter.png"
import itemSimilarityImage from "@/assets/item-similarity.png"
import docChatImage from "@/assets/doc-chat-ncert.png"
import ocrImage from "@/assets/ocr.png"
import comingSoonImage from "@/assets/coming-soon.png"

const Dashboard = () => {
  const [activeTab, setActiveTab] = useState("All")

  const tabs = [
    "All", "AI Generation", "Content Creation", "Education", 
    "Assessment", "Analytics", "AI Tools", "AI Interaction"
  ]

  const getIconForTool = (toolId: string) => {
    const iconMap = {
      "item-generation": Brain,
      "item-writer": PenTool,
      "item-metadata": Database,
      "course-generator": BookOpen,
      "item-rewriter": RefreshCw,
      "item-similarity": GitCompare,
      "course-generator-2": BookOpen,
      "scenario-and": FileText,
      "doc-chat-ncert": MessageSquare,
      "doc-chat-moby": MessageSquare,
      "ocr": ScanLine,
      "essay-evaluation": BarChart3,
      "essay-evaluation-zero": BarChart3,
      "test-forensics": BarChart,
      "image-generator": Image,
      "ai-persona": Bot
    }
    return iconMap[toolId] || Sparkles
  }

  const aiTools = [
    {
      id: "item-generation",
      title: "Item Generation",
      description: "Subjective and objective questions are generated by the items th...",
      path: "/item-generation",
      image: itemGenerationImage,
      category: "AI Generation",
      badge: "New",
      badgeColor: "bg-blue-500",
      icon: Brain
    },
    {
      id: "item-writer",
      title: "Item Writer",
      description: "Objective questions are generated by the items th...",
      path: "/item-writer",
      image: itemWriterImage,
      category: "Content Creation",
      icon: PenTool
    },
    {
      id: "item-metadata",
      title: "Item Metadata",
      description: "AI powered tool knowledge generator helps you...",
      path: "/item-metadata",
      image: itemMetadataImage,
      category: "Analytics",
      icon: Database
    },
    {
      id: "course-generator",
      title: "Course Generator",
      description: "AI assistant course generator that will help yo...",
      path: "/course-generator",
      image: courseGeneratorImage,
      category: "Education",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: BookOpen
    },
    {
      id: "item-rewriter",
      title: "Item Rewriter",
      description: "Easily from old rewritten making the item better an...",
      path: "/item-rewriter",
      image: itemRewriterImage,
      category: "Content Creation",
      icon: RefreshCw
    },
    {
      id: "item-similarity",
      title: "Item Similarity",
      description: "An AI powered tool helps compare questions and...",
      path: "/item-similarity",
      image: itemSimilarityImage,
      category: "Analytics",
      icon: GitCompare
    },
    {
      id: "course-generator-2",
      title: "Course Generator",
      description: "AI assistant course generator that will help yo...",
      path: "/course-generator-2",
      image: courseGeneratorImage,
      category: "Content Creation",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: BookOpen
    },
    {
      id: "scenario-and",
      title: "Scenario and...",
      description: "Generate a variety of scenario and various...",
      path: "/scenario",
      image: comingSoonImage,
      category: "Content Creation",
      icon: FileText
    },
    {
      id: "doc-chat-ncert",
      title: "Doc Chat - NCERT",
      description: "NCERT textbook by asking query, This textbo...",
      path: "/doc-chat-ncert",
      image: docChatImage,
      category: "Education",
      icon: MessageSquare
    },
    {
      id: "doc-chat-moby",
      title: "Doc Chat - Moby-click",
      description: "Verify SAS textbook by asking query, This textbo...",
      path: "/doc-chat-moby",
      image: docChatImage,
      category: "Education",
      icon: MessageSquare
    },
    {
      id: "ocr",
      title: "OCR",
      description: "Optical Character Recognition - Images from...",
      path: "/ocr",
      image: ocrImage,
      category: "AI Tools",
      badge: "New",
      badgeColor: "bg-blue-500",
      icon: ScanLine
    },
    {
      id: "essay-evaluation",
      title: "Essay Evaluation - Fine...",
      description: "Personalized feedback using AI to get some evaluation...",
      path: "/essay-evaluation",
      image: comingSoonImage,
      category: "Assessment",
      icon: BarChart3
    },
    {
      id: "essay-evaluation-zero",
      title: "Essay Evaluation - Zer...",
      description: "A paperless questions are evaluated using SBA and...",
      path: "/essay-evaluation-zero",
      image: comingSoonImage,
      category: "Assessment",
      icon: BarChart3
    },
    {
      id: "test-forensics",
      title: "Test Forensics",
      description: "Find and leverage the power of analytics in online or...",
      path: "/test-forensics",
      image: comingSoonImage,
      category: "Analytics",
      icon: BarChart
    },
    {
      id: "image-generator",
      title: "Image Generator",
      description: "Stable Diffusion - AI image generator your thoughts...",
      path: "/image-generator",
      image: comingSoonImage,
      category: "AI Generation",
      badge: "Popular",
      badgeColor: "bg-green-500",
      icon: Image
    },
    {
      id: "ai-persona",
      title: "AI Persona",
      description: "AI Persona for famous intellectual dialogues in...",
      path: "/ai-persona",
      image: comingSoonImage,
      category: "AI Interaction",
      icon: Bot
    }
  ]

  const filteredTools = activeTab === "All" ? aiTools : aiTools.filter(tool => tool.category === activeTab)

  return (
    <div className="min-h-screen bg-gray-50">
      <AppSidebar />
      
      <div className="ml-0 lg:ml-60 min-h-screen flex flex-col">
        {/* Header */}
        <header className="sticky top-0 z-50 bg-white border-b">
          <div className="flex h-16 items-center justify-between px-4 lg:px-6">
            <div className="flex items-center gap-4 lg:gap-6">
              <h1 className="text-lg lg:text-xl font-semibold text-gray-900">Welcome Back, Shivaraj M!</h1>
              <p className="hidden md:block text-sm text-gray-600">Explore AI-powered tools to enhance your educational content creation</p>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="relative hidden md:block">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input 
                  placeholder="Search AI tools..." 
                  className="pl-10 w-60 lg:w-80"
                />
              </div>
              <ProfileDropdown />
            </div>
          </div>
        </header>

        {/* Stats Cards */}
        <div className="p-4 lg:p-6 pb-4">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6">
            <Card className="p-4 lg:p-6 bg-white border border-gray-200 shadow-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600 mb-1">All</p>
                  <p className="text-xl lg:text-2xl font-bold text-gray-900">16</p>
                  <p className="text-xs text-blue-600">Available Tools</p>
                </div>
                <div className="w-8 h-8 lg:w-10 lg:h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                  <Sparkles className="h-4 w-4 lg:h-5 lg:w-5 text-blue-600" />
                </div>
              </div>
            </Card>

            <Card className="p-4 lg:p-6 bg-white border border-gray-200 shadow-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600 mb-1">Active Subscriptions</p>
                  <p className="text-xl lg:text-2xl font-bold text-gray-900">12</p>
                  <p className="text-xs text-green-600 flex items-center gap-1">
                    <Star className="h-3 w-3" />
                    Active Access
                  </p>
                </div>
                <div className="w-8 h-8 lg:w-10 lg:h-10 bg-green-100 rounded-lg flex items-center justify-center">
                  <Star className="h-4 w-4 lg:h-5 lg:w-5 text-green-600" />
                </div>
              </div>
            </Card>

            <Card className="p-4 lg:p-6 bg-white border border-gray-200 shadow-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600 mb-1">Yet to Subscribe</p>
                  <p className="text-xl lg:text-2xl font-bold text-gray-900">4</p>
                  <p className="text-xs text-purple-600">Advanced Features</p>
                </div>
                <div className="w-8 h-8 lg:w-10 lg:h-10 bg-purple-100 rounded-lg flex items-center justify-center">
                  <ArrowRight className="h-4 w-4 lg:h-5 lg:w-5 text-purple-600" />
                </div>
              </div>
            </Card>

            <Card className="p-4 lg:p-6 bg-white border border-gray-200 shadow-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600 mb-1">Usage Today</p>
                  <p className="text-xl lg:text-2xl font-bold text-gray-900">847</p>
                  <p className="text-xs text-orange-600 flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    Tokens Generated
                  </p>
                </div>
                <div className="w-8 h-8 lg:w-10 lg:h-10 bg-orange-100 rounded-lg flex items-center justify-center">
                  <Clock className="h-4 w-4 lg:h-5 lg:w-5 text-orange-600" />
                </div>
              </div>
            </Card>
          </div>
        </div>

        {/* Main Content */}
        <main className="flex-1 px-4 lg:px-6 pb-6">
          {/* Filter Tabs */}
          <div className="flex gap-2 mb-6 overflow-x-auto">
            {tabs.map((tab) => (
              <Button
                key={tab}
                variant={activeTab === tab ? "default" : "outline"}
                onClick={() => setActiveTab(tab)}
                className={`px-3 lg:px-4 py-2 rounded-lg whitespace-nowrap text-sm ${
                  activeTab === tab 
                    ? "bg-blue-600 text-white" 
                    : "bg-white text-gray-700 border-gray-200 hover:bg-gray-50"
                }`}
              >
                {tab}
              </Button>
            ))}
          </div>

          {/* AI Tools Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 lg:gap-6">
            {filteredTools.map((tool) => {
              const IconComponent = tool.icon
              return (
                <Card key={tool.id} className="group bg-white border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                  <div className="relative">
                    <img 
                      src={tool.image} 
                      alt={tool.title}
                      className="w-full h-32 lg:h-40 object-cover rounded-t-lg"
                    />
                    {/* Tool Icon Overlay */}
                    <div className="absolute top-3 left-3 w-8 h-8 bg-white/90 backdrop-blur-sm rounded-lg flex items-center justify-center shadow-sm">
                      <IconComponent className="h-4 w-4 text-gray-700" />
                    </div>
                    {tool.badge && (
                      <div className={`absolute top-3 right-3 px-2 py-1 rounded text-xs text-white font-medium ${tool.badgeColor}`}>
                        {tool.badge}
                      </div>
                    )}
                    <div className={`absolute bottom-3 right-3 px-2 py-1 rounded text-xs font-medium text-gray-700 bg-white/90 backdrop-blur-sm`}>
                      {tool.category}
                    </div>
                  </div>
                  
                  <CardContent className="p-4">
                    <h3 className="font-semibold text-gray-900 mb-2 line-clamp-1">{tool.title}</h3>
                    <p className="text-sm text-gray-600 mb-4 line-clamp-2">{tool.description}</p>
                    
                    <Link to={tool.path}>
                      <Button 
                        className="w-full bg-blue-600 hover:bg-blue-700 text-white"
                        size="sm"
                      >
                        <Sparkles className="h-4 w-4 mr-2" />
                        Launch App
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              )
            })}
          </div>

          {/* Footer */}
          <footer className="mt-12 pt-8 border-t border-gray-200 text-center">
            <p className="text-sm text-gray-500">
              © 2025 Excelsoftt Technologies Ltd. All rights reserved. | 
              <span className="ml-2">Help Center</span> | 
              <span className="ml-2">Privacy Policy</span> | 
              <span className="ml-2">Terms of Service</span> | 
              <span className="ml-4">Version 1.0.0</span> | 
              <span className="ml-2 flex items-center gap-1">Powered by 
                <img 
                  src="/lovable-uploads/b5b0f5a8-9552-4635-8c44-d5e6f994179c.png" 
                  alt="AI-Levate" 
                  className="h-4 w-auto"
                />
              </span>
            </p>
          </footer>
        </main>
      </div>
    </div>
  )
}

export default Dashboard